### PR TITLE
Various Improvments

### PR DESCRIPTION
**Pull request by DavidMansolino**
Modifications:
  - [x] Various pep8 cleanup.
  - [x] Handle package relative path (e.g.: `<mesh filename="package://ur_description/meshes/ur5/visual/base.dae"/>`)
  - [x] Write mesh coordinates on one line.
  - [x] Switch to PBR.
  - [x] Fix missing shapes.
  - [x] Fix transformation issue.
  - [x] Add position sensors.
  - [x] Move math fucntion in math module
  - [x] Support basic sensors:
    - [x] Camera
    - [x] Lidar
    - [x] IMU (accelerometer+gyro+compass).
  - [x] PEP8 travis test.
  - [x] Improve README

### CODE REVIEW

**Comment by DavidMansolino** [comment]
I can now use the script to export the universal robot arm with PBR by default, but some shapes are still missing:
empty_1

**Comment by DavidMansolino** [comment]
The problem with the missing shapes was due to the fact that some collada geometries can have several primitives which should be considered as different indexedFaceSets.

**Comment by DavidMansolino** [comment]
The orientation issue reported in #11 is almost fixed (remains to handle joint position limit that does not contain the 0 position):
empty_3

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Pull request merged**
